const API_URL = 'https://trekly-app-1e3b0be8eb44.herokuapp.com';

export const config = {
  API_ENDPOINTS: {
    LOGIN: `${API_URL}/auth/login`,
    REFRESH_TOKEN: `${API_URL}/auth/token/refresh`,
    REGISTER: `${API_URL}/auth/register`,
    EXERCISES: `${API_URL}/exercises/exercise`,
    EXERCISE: `${API_URL}/exercises`,
    BODY_PARTS: `${API_URL}/exercises/bodyParts`,
    EQUIPMENT: `${API_URL}/exercises/equipment`,
    TARGETS: `${API_URL}/exercises/targetList`,
    SAVE_ROUTINE: `${API_URL}/routines/save`,
    DELETE_ROUTINE: `${API_URL}/routines/delete`,
    UPDATE_ROUTINE: `${API_URL}/routines/update`,
    GET_ROUTINES: `${API_URL}/routines/all`,
    USER_PROFILE: `${API_URL}/users/user`,
    USER_PROFILES: `${API_URL}/users/all`,
    FETCH_WORKOUTS: `${API_URL}/workouts/all`,
    SAVE_WORKOUT: `${API_URL}/workouts/save`,
    DELETE_WORKOUT: `${API_URL}/workouts/delete`,
    GET_IMAGE: `${API_URL}/images`,
    UPLOAD_IMAGE: `${API_URL}/images/upload`,
    FOLLOW: `${API_URL}/follows/follow`,
    UNFOLLOW: `${API_URL}/follows/unfollow`,
    FOLLOWS: `${API_URL}/follows`,
    LIKE: `${API_URL}/likes/like`,
    UNLIKE: `${API_URL}/likes/unlike`,
    WORKOUT_LIKES: `${API_URL}/likes`,
    WORKOUT_COMMENTS: `${API_URL}/comments`,
    ADD_COMMENT:`${API_URL}/comments/comment`,
    DELETE_COMMENT:`${API_URL}/comments/delete`,
    CHECK_ACHIEVEMENTS: `${API_URL}/achievements/check`,
    FETCH_USER_ACHIEVEMENTS: `${API_URL}/achievements`,
    FETCH_NOTIFICATIONS: `${API_URL}/notifications/all`,
    DELETE_ACCOUNT: `${API_URL}/users/delete_account`,
    REPORT_WORKOUT: `${API_URL}/reports/report_workout`,
    REPORT_USER: `${API_URL}/reports/report_user`,
    BLOCK_USER: `${API_URL}/reports/block_user`,
  },
};